# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 小龙龙的个人博客
email: puronglong@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  蒲荣龙|小龙龙的个人博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.puronglong.com" # the base hostname & protocol for your site
github_username:  puronglong

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page:num"

# 代码高亮
highlighter: rouge
